local f = assert(io.open("ui/CommunityBuilds.lua", "r"))
local s = f:read("*a"); f:close()
assert(s:find('Discord Build Post or Channel:', 1, true), 'Discord field label missing')
assert(s:find('clearLinkBtn', 1, true), 'clear button missing')
assert(s:find('Open Discord Guide', 1, true), 'open guide action missing')
assert(s:find('M.EditBuild%(p%._editingId, editTitleBox:GetText%(%), editDescBox:GetText%(%), editLinkBox:GetText%(%)%)'), 'link not saved through Edit Build')
assert(s:find('link:match("^https://discord%.com/channels/(%d+)/(%d+)/(%d+)/?$")', 1, true) and s:find('link:match("^https://discord%.com/channels/(%d+)/(%d+)/?$")', 1, true), 'Discord channel-link validator missing')
assert(s:find('https://discord.com/channels/%s/%s', 1, true), 'Discord channel-link normalization missing')
print('discord build link UI tests passed')
